package com.esoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccessTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccessTokenAllPropertiesEquals(AccessToken expected, AccessToken actual) {
        assertAccessTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertAccessTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccessTokenAllUpdatablePropertiesEquals(AccessToken expected, AccessToken actual) {
        assertAccessTokenUpdatableFieldsEquals(expected, actual);
        assertAccessTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccessTokenAutoGeneratedPropertiesEquals(AccessToken expected, AccessToken actual) {
        assertThat(actual)
            .as("Verify AccessToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccessTokenUpdatableFieldsEquals(AccessToken expected, AccessToken actual) {
        assertThat(actual)
            .as("Verify AccessToken relevant properties")
            .satisfies(a -> assertThat(a.getHashedToken()).as("check hashedToken").isEqualTo(expected.getHashedToken()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getUpdatedDate()).as("check updatedDate").isEqualTo(expected.getUpdatedDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccessTokenUpdatableRelationshipsEquals(AccessToken expected, AccessToken actual) {
        // empty method
    }
}
